language: python
# Test against 2.7, 3.3 and 3.4
# We don't support 3.2 because the pem library doesn't support it
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
# command to define we should test against the latest version of all supported
# versions of django (1.8.x, 1.9.x, 1.10.x, 1.11.x)
env:
  - DJANGO_INSTALL=django\<1.8.99
  - DJANGO_INSTALL=django\<1.9.99
  - DJANGO_INSTALL=django\<1.10.99
  - DJANGO_INSTALL=django\<1.11.99
  - DJANGO_INSTALL=git+https://github.com/django/django.git\#egg=django
# command to install dependencies (mock & nose are already installed)
install:
  - pip install $DJANGO_INSTALL
  - python setup.py install
  - pip install django-nose coverage mock
# command to run tests
script: python manage.py test --settings 'test_settings'
matrix:
  fast_finish: true
  allow_failures:
    # pypy testing support is experimental
    - python: "pypy"

    # Tests against the master branch may break
    - env: DJANGO_INSTALL=git+https://github.com/django/django.git\#egg=django
  exclude:
    # Django 1.9 onward doesn't support Python 3.3
    - python: "3.3"
      env: DJANGO_INSTALL=django\<1.9.99

    # Django 1.10 onward doesn't support Python 3.3
    - python: "3.3"
      env: DJANGO_INSTALL=django\<1.10.99

    # Django 1.11 onward doesn't support Python 3.3
    - python: "3.3"
      env: DJANGO_INSTALL=django\<1.11.99

    # Django latest onward doesn't support Python 3.3
    - python: "3.3"
      env: DJANGO_INSTALL=git+https://github.com/django/django.git\#egg=django
# turn off email notifications
notifications:
  email: false
deploy:
  # Allow travis-ci to deploy new tags to PyPI
  provider: pypi
  user: ofa
  password:
    secure: mynPDpo4PHD8VjYJ03Yui2Xr2ICxP56DEOfE4IOr8RRorqJH7BtrYrX4TkqYLb81IR9Mgnzbk9wslq7ShGfYhXgSFWujDPyCsliPG1v826FXEMe3U7yT5B+Vrt7xA6FkImCuZIROmrGL9KSbobFTsBnTL6/LxMZ6pTYCJiXyf9E=
  on:
    tags: true
    repo: ofa/django-bouncy
